// Question array which contains question objects
export const questions = [
    {
        question: "Which of the following is not a valid JavaScript data type?",
        option1: "Number",
        option2: "Float",
        option3: "String",
        option4: "Boolean",
        answer: 2, // Float is not a valid JS data type
    },
    {
        question: "What will be the output of the following code?<br> console.log(2 + '2');",
        option1: "4",
        option2: "'22'",
        option3: "22",
        option4: "Error",
        answer: 2,
    },
    {
        question: "Which function is used to convert a JSON string into a JavaScript object?",
        option1: "JSON.stringify()",
        option2: "JSON.parse()",
        option3: "JSON.encode()",
        option4: "JSON.toObject()",
        answer: 2,
    },
    {
        question: "What is the correct way to declare a JavaScript array?",
        option1: "var array = {};",
        option2: "var array = [];",
        option3: "var array = ();",
        option4: "var array = new Array();",
        answer: 2,
    },
    {
        question: "What does the 'typeof' operator in JavaScript return?",
        option1: "The data type of a variable",
        option2: "The value of a variable",
        option3: "The length of a variable",
        option4: "The name of a variable",
        answer: 1,
    },
    {
        question: "Which of the following is not a loop structure in JavaScript?",
        option1: "for",
        option2: "while",
        option3: "loop",
        option4: "do...while",
        answer: 3,
    },
    {
        question: "What will be the output of the following code?<br> var x = 10;<br> var y = '5';<br> console.log(x + y);",
        option1: "15",
        option2: "'105'",
        option3: "105",
        option4: "Error",
        answer: 2,
    },
    {
        question: "In JavaScript, what does the value 'NaN' represent?",
        option1: "Not a Number, used to represent mathematical errors",
        option2: "A large random number",
        option3: "Infinity",
        option4: "A non-terminating decimal",
        answer: 1,
    },
    {
        question: "Which of the following is NOT a valid way to declare a function in JavaScript?",
        option1: "function myFunction() {}",
        option2: "var myFunction = function() {};",
        option3: "const myFunction = () => {};",
        option4: "const function() {};",
        answer: 4,
    },
    {
        question: "What is the correct way to write a single-line comment in JavaScript?",
        option1: "/* This is a comment",
        option2: "'This is a comment'",
        option3: "// This is a comment",
        option4: "/* This is a comment */",
        answer: 3,
    },
    {
        question: "What is the result of the following expression?<br>3 + 2 + '7'",
        option1: "'57'",
        option2: "'327'",
        option3: "'12'",
        option4: "'37'",
        answer: 1,
    },
    {
        question: "How can you check if a variable is an array in JavaScript?",
        option1: "typeof variable",
        option2: "isArray(variable)",
        option3: "variable.isarray()",
        option4: "Array.isArray(variable)",
        answer: 4,
    },
    {
        question: "How do you access the first element of an array called 'myArray'?",
        option1: "myArray.first",
        option2: "myArray[1]",
        option3: "myArray.firstElement",
        option4: "myArray[0]",
        answer: 4,
    },
    {
        question: "Which of the following is true about JavaScript?",
        option1: "It is case-insensitive",
        option2: "It requires data types to be explicitly declared",
        option3: "It supports automatic type conversion",
        option4: "It does not support object-oriented programming",
        answer: 3,
    },
    {
        question: "What does the '===' operator do in JavaScript?",
        option1: "Checks equality without type checking",
        option2: "Checks equality with type checking",
        option3: "Assigns a value to a variable",
        option4: "Converts a string to a number",
        answer: 2,
    },
    {
        question: "What does the 'Math.random()' function return?",
        option1: "A random integer between 0 and 1",
        option2: "A random number between 1 and 100",
        option3: "A random floating-point number between 0 and 1",
        option4: "A random decimal between 0 and 100",
        answer: 3,
    },
    {
        question: "How can you convert a string to lowercase in JavaScript?",
        option1: "strlowercase()",
        option2: "str.toLowerCase()",
        option3: "strconvertToLower()",
        option4: "str.toLower()",
        answer: 2,
    },
    {
        question: "Which method is used to add a new element at the end of an array?",
        option1: "push()",
        option2: "unshift()",
        option3: "add()",
        option4: "append()",
        answer: 1,
    },
    {
        question: "What is the purpose of the 'use strict' directive in JavaScript?",
        option1: "To enable strict mode and enforce cleaner code",
        option2: "To enable dynamic typing",
        option3: "To allow implicit conversions",
        option4: "To disable type checking",
        answer: 1,
    },
    {
        question: "Which built-in method removes the last element from an array and returns it?",
        option1: "pop()",
        option2: "shift()",
        option3: "splice()",
        option4: "slice()",
        answer: 1,
    }
];
